### ISSUE TITLE
Add timestamp to CSV output?

### ISSUE THREAD

**Issue by AnthonyBe** [nikiluk/automate-ookla-speedtest#2]
Would it be possible to include a timestamp in the CSV output?

Thanks!

**Comment by nikiluk** [comment]
Hi @AnthonyBe. This is possible to do by hard-coding the timestamp in `test-csv.ps1`, however the timestamp will differ from the real one that the ookla server returns. 

Instead of doing this, I recommend to run `test.ps1` and then convert internetspeed.json result into CSV using this converter for example. https://www.convertcsv.com/json-to-csv.htm

**Comment by nikiluk** [comment]
Also @jamierpond has just added the `timestamp` column using pure python script `python-csv`, which you can test.
